### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by kuraga** [text-machine-lab/sentimental#1]
@jgc128 , thanks for your package very much! I have some questions, please:

1) Where list of Russian words come from? (The words itself: why these words not others?)

2) Where their scores come from? Is it an experts' opinion?

3) Which form are the words, exactly? Are they formulated by linguists or preprocessed by some application?

4) Why some words are duplicated?

Thanks!

**Comment by jgc128** [comment]
Unfortunately, I don't have a precise source of these words. As I remember, some lexicon was used and these words came directly from it without any preprocessing.

**Comment by kuraga** [comment]
Oh...
